export const SET_CURRENT_USER   = 'SET_CURRENT_USER'
export const TOGGLE_MENU_ACTIVE = 'TOGGLE_MENU_ACTIVE'
export const SET_PATIENT        = 'SET_PATIENT'
export const SET_LIST           = 'SET_LIST'
export const INCREMENT_STEP     = 'INCREMENT_STEP'
export const DECREMENT_STEP     = 'DECREMENT_STEP'